server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway-service
  profiles:
    default: ${ACTIVATED_PROPERTIES}
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  instance:
    prefer-ip-address: true
    hostname: gateway-service
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

