server:
  port: 9001
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neo_shikha
    username: neo
    password: shikha
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: NeoShikhaHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      fail-fast: true
