spring:
  application:
    name: authorization-service
  profiles:
    default: ${ACTIVATED_PROPERTIES}
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
