server:
  port: 8888
  forward-headers-strategy: framework

spring:
  application:
    name: config-service
  cloud:
    config:
      fail-fast: false
      server:
        native:
          search-locations: classpath:/shared/${NEOSHIKHA_DEPLOY_MODE}
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    hostname: config-service
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

